name: freecad
base: core22
adopt-info: freecad
donation: https://wiki.freecad.org/Donate
issues: https://github.com/FreeCAD/FreeCAD-snap/issues
website: https://freecad.org
summary: An open source parametric 3D CAD modeler
description: |
  FreeCAD is a parametric 3D modeler. Parametric modeling
  allows you to easily modify your design by going back into
  your model history and changing its parameters. FreeCAD is
  open source (LGPL license) and completely modular, allowing
  for very advanced extension and customization.

  FreeCAD is multiplatfom, and reads and writes many open
  file formats such as STEP, IGES, STL and others.

  Please also consider RealThunder's well-known FreeCAD fork
  `freecad-realthunder`: https://snapcraft.io/freecad-realthunder

  Commands:
        freecad:      Run FreeCAD
        freecad.cmd:  Run FreeCAD command line interface
        freecad.pip:  Install python packages for user (not system-wide).
                      E.g. `freecad.pip install py_slvs` for Assembly3.

grade: devel
confinement: strict
compression: lzo
license: LGPL-2.0-or-later
assumes: [snapd2.55.3] # for cups interface & private shared memory

layout:
  /usr/share/X11:
    symlink: $SNAP/kf5/usr/share/X11
  /usr/bin/mpirun: # ElmerSolver_mpi
    symlink: $SNAP/usr/bin/orterun
  /usr/share/openmpi:
    symlink: $SNAP/usr/share/openmpi
  /etc/openmpi:
    bind: $SNAP/etc/openmpi
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/openmpi:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/openmpi
  /usr/bin/orted:
    symlink: $SNAP/usr/bin/orted
  /usr/share/pmix:
    symlink: $SNAP/usr/share/pmix
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pmix:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pmix
  /etc/matplotlibrc:
    bind-file: $SNAP/etc/matplotlibrc
  /usr/share/matplotlib:
    symlink: $SNAP/usr/share/matplotlib
  /usr/share/qt5:
    symlink: $SNAP/kf5/usr/share/qt5
  /usr/bin/dot: # Graphviz for dependency graph
    symlink: $SNAP/usr/bin/dot
  /usr/bin/unflatten: # Graphviz for dependency graph
    symlink: $SNAP/usr/bin/unflatten
  /usr/share/povray-3.7: # Raytracing
    symlink: $SNAP/usr/share/povray-3.7

plugs:
  shared-memory:
    private: true
  # QT5 libs
  kf5-core22:
    content: kf5-core22-all
    interface: content
    default-provider: kf5-core22
    target: $SNAP/kf5

environment:
  LD_LIBRARY_PATH: "$SNAP/usr/lib/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/:$SNAP/kf5/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/:$SNAP/kf5/usr/lib:/$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack:$LD_LIBRARY_PATH"
  LD_PRELOAD: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libstubchown.so
  FREECAD_USER_HOME: $SNAP_USER_COMMON
  GIT_EXEC_PATH: $SNAP/usr/lib/git-core
  GIT_TEMPLATE_DIR: $SNAP/usr/share/git-core/templates
  GIT_CONFIG_NOSYSTEM: 1
  ELMER_HOME: $SNAP/usr
  PYTHONPYCACHEPREFIX: $SNAP_USER_COMMON/.pycache
  PYTHONUSERBASE: $SNAP_USER_COMMON/.local
  PIP_USER: 1
  PYTHONPATH: &pypath $PYTHONUSERBASE/lib/python3.10/site-packages:$SNAP/lib/python3.10/site-packages:$SNAP/usr/lib/python3/dist-packages
  SNAP_PYTHONPATH: *pypath
  QT_QPA_PLATFORM: xcb # Coin3D cannot run on Wayland
  POVINI: $SNAP/etc/povray/3.7/povray.ini # Raytracing

apps:
  freecad:
    command: usr/bin/chown
    extensions: [kde-neon]
#    common-id: org.freecad.FreeCAD.desktop
#    desktop: usr/share/applications/org.freecad.FreeCAD.desktop
    plugs: &plugs
      - home
      - opengl
      - removable-media
      - gsettings
      - network
      - browser-support
      - unity7
      - cups
      - shared-memory
    command-chain:
      - snap/command-chain/desktop-launch
  cmd:
    command: usr/bin/FreeCADCmd
    extensions: [kde-neon]
    plugs: *plugs
  pip:
    command: bin/pip
    plugs: *plugs

package-repositories:
  - type: apt
    components:
      - main
    suites:
      - jammy
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com

parts:
  freecad:
    plugin: meson
    source: $CRAFT_PROJECT_DIR/snap/local/stub-chown
    source-type: local
    meson-parameters:
      - --prefix=/usr
    build-snaps:
      - freecad-deps-core22/candidate
      - kde-qt5-core22-sdk
    stage-snaps:
      - freecad-deps-core22/candidate
    build-packages:
      - meson
      - g++
      - git
      - libboost-all-dev
      - libsimage-dev # optional
      - libspnav-dev # optional
      - libeigen3-dev
      - libgts-bin
      - libgts-dev
      - libkdtree++-dev
      - libmedc-dev
      - libopencv-dev
      - libproj-dev
      - libx11-dev
      - libxerces-c-dev
      - libyaml-cpp-dev
      - swig
      - python3-dev
      - libcoin-dev
      - libvtk7-dev
      - libpyside2-dev
      - libshiboken2-dev
      - pybind11-dev
      - libfreeimage-dev
      - openscad
      - python3-pivy
      - python3-matplotlib
    stage-packages:
      - libaec0
      - libboost-filesystem1.74.0
      - libboost-program-options1.74.0
      - libboost-python1.74.0
      - libboost-regex1.74.0
      - libboost-system1.74.0
      - libboost-thread1.74.0
      - libboost-date-time1.74.0
      - libhdf5-openmpi-103
      - libhwloc15
      - libilmbase25
      - libjxr0
      - libmedc11
      - libmed11
      - libopenexr25
      - libopenmpi3
      - on amd64: [libpsm-infinipath1]
      - libpython3.10
      - libpython3.10-minimal
      - libpython3.10-stdlib
      - libraw20
      - libspnav0
      - libsz2
      - libxerces-c3.2
      - libyaml-cpp0.7
      - python3-tk # FEM
      - python3-yaml # FEM
      - python3-numba # FEM (fcFEM)
      - python3-scipy # FEM
      - python3-numpy
      - python3-matplotlib
      - python3-six
      - python3-packaging # Path
      - python3-pyparsing
      - python3-setuptools-scm
      - python3-collada # DAE import
      - python3-cycler
      - python3-dateutil
      - python3-git
      - python3-ply # OpenSCAD
      - python3-pivy
      - python3-pyside2.qtcore
      - python3-pyside2.qtgui
      - python3-pyside2.qtsvg
      - python3-pyside2.qtwidgets
      - python3-pyside2.qtnetwork
      - python3-pyside2.qtuitools
      - python3-requests
      - calculix-ccx # FEM
      - libcoin80c
      - libfreeimage3
      - libtbb2
      - libvtk7.1p
      - elmerfem-csc # FEM
      - openscad  # OpenSCAD
    override-build: |
      craftctl default

  python-packages:
    plugin: python
    source: .
    source-type: local
    build-packages:
      - libsuitesparse-dev
    stage-packages:
      - python3-distutils # pip
      - libamd2 # scikit-sparse
      - libcamd2 # scikit-sparse
      - libccolamd2 # scikit-sparse
      - libcholmod3 # scikit-sparse
      - libcolamd2 # scikit-sparse
      - libsuitesparseconfig5 # scikit-sparse
    python-packages:
      - ifcopenshell == 0.8.0 # BIM
      - opencamlib # CAM
      - pip
      - scikit-sparse
    stage:
      - -pyvenv.cfg
      - -lib/python3.10/site-packages/scipy*
      - -lib/python3.10/site-packages/numpy*

  cleanup:
    after: [freecad, python-packages]
    plugin: nil
    build-snaps: [kf5-core22-sdk]
    override-prime: |
      set -eux
      for snap in "kf5-core22-sdk"; do  # List all content-snaps you're using here
        cd "/snap/$snap/current" && \
        find . -type f,l \
          -not -name 'libboost_filesystem.so*' \
          -exec echo "Removing $CRAFT_PRIME/{} and $CRAFT_PRIME/usr/{}\n" \
          -exec rm -f "$CRAFT_PRIME/{}" "$CRAFT_PRIME/usr/{}" \;
      done
      for cruft in bug lintian man; do
        rm -rf $CRAFT_PRIME/usr/share/$cruft
      done
#      find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -not -name 'ThirdPartyLibraries.html' -not -name 'LICENSE.html' -delete
#      find $CRAFT_PRIME/usr/share -type d -empty -delete
#      find $CRAFT_PRIME/usr/lib -type f,l \
#        -name 'libQt*.so*' `# remove all Qt libs pulled in from Ubuntu repos` \
#        -not -name 'libQt5Gamepad.so*' -delete `# for OpenSCAD`
